[project]
name = "architext"
version = "0.1.68"
description = "The Context Engineering framework for building smarter, more reliable AI Agents."
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[tool.setuptools.packages.find]
where = ["."]
include = ["architext*"]